Update Minor Version Maven Dependencies
kagemomiji/airsonic-advanced pull request #397
Opened 2024-03-18 10:25 UTC by thewriteway

List of version changes and success status:
![image](https://github.com/kagemomiji/airsonic-advanced/assets/13290180/e15d4a7a-c88b-44c6-99c3-d34d9365b9b1)
Regression fixes included.

2024-04-01 10:27 UTC, thewriteway commented
Hi Kagemonji, I tried to update as many minor dependencies as possible in this PR.  I cant tell if the build tests are too sensitive or my PR code isn't very compatible.

2024-04-06 13:22 UTC, kagemomiji requested changes
@thewriteway 

Thank you for submitting the updates.

Upon reviewing the CI errors, it appears to be an issue related to logback dependencies, so I believe that changing the logback version is the direct cause of the error. 
I have also commented on other changes that need to be made.

2024-04-06 13:22 UTC, kagemomiji commented on pom.xml
> +                            </ignoredNonTestScopedDependencies>
It seems unnecessary definition.
```suggestion
```

2024-04-22 10:36 UTC, kagemomiji approved these changes
LGTM

2024-04-22 10:43 UTC, merged